// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.6
// source: sessionpb/session.proto

package sessionpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SessionData holds AES-GCM key and nonce for decrypting vault data.
type VaultKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`     // AES-GCM key
	Nonce         []byte                 `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"` // AES-GCM nonce
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VaultKey) Reset() {
	*x = VaultKey{}
	mi := &file_sessionpb_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VaultKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaultKey) ProtoMessage() {}

func (x *VaultKey) ProtoReflect() protoreflect.Message {
	mi := &file_sessionpb_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VaultKey.ProtoReflect.Descriptor instead.
func (*VaultKey) Descriptor() ([]byte, []int) {
	return file_sessionpb_session_proto_rawDescGZIP(), []int{0}
}

func (x *VaultKey) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *VaultKey) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

// LoginRequest is used to initiate a session.
type LoginRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	VaultPath string                 `protobuf:"bytes,1,opt,name=vault_path,json=vaultPath,proto3" json:"vault_path,omitempty"`
	// Session duration (e.g. "30s", "10m").
	Duration      string    `protobuf:"bytes,2,opt,name=duration,proto3" json:"duration,omitempty"`
	VaultKey      *VaultKey `protobuf:"bytes,3,opt,name=vault_key,json=vaultKey,proto3" json:"vault_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_sessionpb_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sessionpb_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_sessionpb_session_proto_rawDescGZIP(), []int{1}
}

func (x *LoginRequest) GetVaultPath() string {
	if x != nil {
		return x.VaultPath
	}
	return ""
}

func (x *LoginRequest) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

func (x *LoginRequest) GetVaultKey() *VaultKey {
	if x != nil {
		return x.VaultKey
	}
	return nil
}

// SessionRequest identifies a vault session by path.
type SessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VaultPath     string                 `protobuf:"bytes,1,opt,name=vault_path,json=vaultPath,proto3" json:"vault_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionRequest) Reset() {
	*x = SessionRequest{}
	mi := &file_sessionpb_session_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionRequest) ProtoMessage() {}

func (x *SessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sessionpb_session_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionRequest.ProtoReflect.Descriptor instead.
func (*SessionRequest) Descriptor() ([]byte, []int) {
	return file_sessionpb_session_proto_rawDescGZIP(), []int{2}
}

func (x *SessionRequest) GetVaultPath() string {
	if x != nil {
		return x.VaultPath
	}
	return ""
}

var File_sessionpb_session_proto protoreflect.FileDescriptor

const file_sessionpb_session_proto_rawDesc = "" +
	"\n" +
	"\x17sessionpb/session.proto\x12\tsessionpb\x1a\x1bgoogle/protobuf/empty.proto\"2\n" +
	"\bVaultKey\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\fR\x05nonce\"{\n" +
	"\fLoginRequest\x12\x1d\n" +
	"\n" +
	"vault_path\x18\x01 \x01(\tR\tvaultPath\x12\x1a\n" +
	"\bduration\x18\x02 \x01(\tR\bduration\x120\n" +
	"\tvault_key\x18\x03 \x01(\v2\x13.sessionpb.VaultKeyR\bvaultKey\"/\n" +
	"\x0eSessionRequest\x12\x1d\n" +
	"\n" +
	"vault_path\x18\x01 \x01(\tR\tvaultPath2\xc1\x01\n" +
	"\aSession\x128\n" +
	"\x05Login\x12\x17.sessionpb.LoginRequest\x1a\x16.google.protobuf.Empty\x12?\n" +
	"\rGetSessionKey\x12\x19.sessionpb.SessionRequest\x1a\x13.sessionpb.VaultKey\x12;\n" +
	"\x06Logout\x12\x19.sessionpb.SessionRequest\x1a\x16.google.protobuf.EmptyB;Z9github.com/ladzaretti/vlt-cli/vaultdaemon/proto/sessionpbb\x06proto3"

var (
	file_sessionpb_session_proto_rawDescOnce sync.Once
	file_sessionpb_session_proto_rawDescData []byte
)

func file_sessionpb_session_proto_rawDescGZIP() []byte {
	file_sessionpb_session_proto_rawDescOnce.Do(func() {
		file_sessionpb_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sessionpb_session_proto_rawDesc), len(file_sessionpb_session_proto_rawDesc)))
	})
	return file_sessionpb_session_proto_rawDescData
}

var file_sessionpb_session_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_sessionpb_session_proto_goTypes = []any{
	(*VaultKey)(nil),       // 0: sessionpb.VaultKey
	(*LoginRequest)(nil),   // 1: sessionpb.LoginRequest
	(*SessionRequest)(nil), // 2: sessionpb.SessionRequest
	(*emptypb.Empty)(nil),  // 3: google.protobuf.Empty
}
var file_sessionpb_session_proto_depIdxs = []int32{
	0, // 0: sessionpb.LoginRequest.vault_key:type_name -> sessionpb.VaultKey
	1, // 1: sessionpb.Session.Login:input_type -> sessionpb.LoginRequest
	2, // 2: sessionpb.Session.GetSessionKey:input_type -> sessionpb.SessionRequest
	2, // 3: sessionpb.Session.Logout:input_type -> sessionpb.SessionRequest
	3, // 4: sessionpb.Session.Login:output_type -> google.protobuf.Empty
	0, // 5: sessionpb.Session.GetSessionKey:output_type -> sessionpb.VaultKey
	3, // 6: sessionpb.Session.Logout:output_type -> google.protobuf.Empty
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sessionpb_session_proto_init() }
func file_sessionpb_session_proto_init() {
	if File_sessionpb_session_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sessionpb_session_proto_rawDesc), len(file_sessionpb_session_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sessionpb_session_proto_goTypes,
		DependencyIndexes: file_sessionpb_session_proto_depIdxs,
		MessageInfos:      file_sessionpb_session_proto_msgTypes,
	}.Build()
	File_sessionpb_session_proto = out.File
	file_sessionpb_session_proto_goTypes = nil
	file_sessionpb_session_proto_depIdxs = nil
}
