// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.6
// source: sessionpb/session.proto

package sessionpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CipherData holds secure material used in authenticated sessions.
type CipherData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthPhc       string                 `protobuf:"bytes,1,opt,name=auth_phc,json=authPhc,proto3" json:"auth_phc,omitempty"` // PHC string for the authentication key
	KdfPhc        string                 `protobuf:"bytes,2,opt,name=kdf_phc,json=kdfPhc,proto3" json:"kdf_phc,omitempty"`    // PHC string for the KDF
	Nonce         []byte                 `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`                    // Nonce (binary)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CipherData) Reset() {
	*x = CipherData{}
	mi := &file_sessionpb_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CipherData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CipherData) ProtoMessage() {}

func (x *CipherData) ProtoReflect() protoreflect.Message {
	mi := &file_sessionpb_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CipherData.ProtoReflect.Descriptor instead.
func (*CipherData) Descriptor() ([]byte, []int) {
	return file_sessionpb_session_proto_rawDescGZIP(), []int{0}
}

func (x *CipherData) GetAuthPhc() string {
	if x != nil {
		return x.AuthPhc
	}
	return ""
}

func (x *CipherData) GetKdfPhc() string {
	if x != nil {
		return x.KdfPhc
	}
	return ""
}

func (x *CipherData) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

// LoginRequest is used to initiate a session.
type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VaultPath     string                 `protobuf:"bytes,1,opt,name=vault_path,json=vaultPath,proto3" json:"vault_path,omitempty"`
	CipherData    *CipherData            `protobuf:"bytes,2,opt,name=cipher_data,json=cipherData,proto3" json:"cipher_data,omitempty"`
	Duration      string                 `protobuf:"bytes,3,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_sessionpb_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sessionpb_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_sessionpb_session_proto_rawDescGZIP(), []int{1}
}

func (x *LoginRequest) GetVaultPath() string {
	if x != nil {
		return x.VaultPath
	}
	return ""
}

func (x *LoginRequest) GetCipherData() *CipherData {
	if x != nil {
		return x.CipherData
	}
	return nil
}

func (x *LoginRequest) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

// SessionRequest identifies a vault session by path.
type SessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VaultPath     string                 `protobuf:"bytes,1,opt,name=vault_path,json=vaultPath,proto3" json:"vault_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionRequest) Reset() {
	*x = SessionRequest{}
	mi := &file_sessionpb_session_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionRequest) ProtoMessage() {}

func (x *SessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sessionpb_session_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionRequest.ProtoReflect.Descriptor instead.
func (*SessionRequest) Descriptor() ([]byte, []int) {
	return file_sessionpb_session_proto_rawDescGZIP(), []int{2}
}

func (x *SessionRequest) GetVaultPath() string {
	if x != nil {
		return x.VaultPath
	}
	return ""
}

var File_sessionpb_session_proto protoreflect.FileDescriptor

const file_sessionpb_session_proto_rawDesc = "" +
	"\n" +
	"\x17sessionpb/session.proto\x12\tsessionpb\x1a\x1bgoogle/protobuf/empty.proto\"V\n" +
	"\n" +
	"CipherData\x12\x19\n" +
	"\bauth_phc\x18\x01 \x01(\tR\aauthPhc\x12\x17\n" +
	"\akdf_phc\x18\x02 \x01(\tR\x06kdfPhc\x12\x14\n" +
	"\x05nonce\x18\x03 \x01(\fR\x05nonce\"\x81\x01\n" +
	"\fLoginRequest\x12\x1d\n" +
	"\n" +
	"vault_path\x18\x01 \x01(\tR\tvaultPath\x126\n" +
	"\vcipher_data\x18\x02 \x01(\v2\x15.sessionpb.CipherDataR\n" +
	"cipherData\x12\x1a\n" +
	"\bduration\x18\x03 \x01(\tR\bduration\"/\n" +
	"\x0eSessionRequest\x12\x1d\n" +
	"\n" +
	"vault_path\x18\x01 \x01(\tR\tvaultPath2\xc0\x01\n" +
	"\aSession\x128\n" +
	"\x05Login\x12\x17.sessionpb.LoginRequest\x1a\x16.google.protobuf.Empty\x12>\n" +
	"\n" +
	"GetSession\x12\x19.sessionpb.SessionRequest\x1a\x15.sessionpb.CipherData\x12;\n" +
	"\x06Logout\x12\x19.sessionpb.SessionRequest\x1a\x16.google.protobuf.EmptyB;Z9github.com/ladzaretti/vlt-cli/vaultdaemon/proto/sessionpbb\x06proto3"

var (
	file_sessionpb_session_proto_rawDescOnce sync.Once
	file_sessionpb_session_proto_rawDescData []byte
)

func file_sessionpb_session_proto_rawDescGZIP() []byte {
	file_sessionpb_session_proto_rawDescOnce.Do(func() {
		file_sessionpb_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sessionpb_session_proto_rawDesc), len(file_sessionpb_session_proto_rawDesc)))
	})
	return file_sessionpb_session_proto_rawDescData
}

var file_sessionpb_session_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_sessionpb_session_proto_goTypes = []any{
	(*CipherData)(nil),     // 0: sessionpb.CipherData
	(*LoginRequest)(nil),   // 1: sessionpb.LoginRequest
	(*SessionRequest)(nil), // 2: sessionpb.SessionRequest
	(*emptypb.Empty)(nil),  // 3: google.protobuf.Empty
}
var file_sessionpb_session_proto_depIdxs = []int32{
	0, // 0: sessionpb.LoginRequest.cipher_data:type_name -> sessionpb.CipherData
	1, // 1: sessionpb.Session.Login:input_type -> sessionpb.LoginRequest
	2, // 2: sessionpb.Session.GetSession:input_type -> sessionpb.SessionRequest
	2, // 3: sessionpb.Session.Logout:input_type -> sessionpb.SessionRequest
	3, // 4: sessionpb.Session.Login:output_type -> google.protobuf.Empty
	0, // 5: sessionpb.Session.GetSession:output_type -> sessionpb.CipherData
	3, // 6: sessionpb.Session.Logout:output_type -> google.protobuf.Empty
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sessionpb_session_proto_init() }
func file_sessionpb_session_proto_init() {
	if File_sessionpb_session_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sessionpb_session_proto_rawDesc), len(file_sessionpb_session_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sessionpb_session_proto_goTypes,
		DependencyIndexes: file_sessionpb_session_proto_depIdxs,
		MessageInfos:      file_sessionpb_session_proto_msgTypes,
	}.Build()
	File_sessionpb_session_proto = out.File
	file_sessionpb_session_proto_goTypes = nil
	file_sessionpb_session_proto_depIdxs = nil
}
