version: 2

builds:
  - id: "vlt"
    main: ./cmd/vlt
    binary: vlt
    goos:
      - linux
    ldflags:
      - -X github.com/ladzaretti/vlt-cli/cli.Version={{ .Version }}

  - id: "vltd"
    main: ./cmd/vltd
    binary: vltd
    goos:
      - linux
    ldflags:
      - -X main.Version={{ if .IsSnapshot }}{{ .Version }}{{ else }}{{ .Tag }}{{ end }}

snapshot:
  version_template: "{{ .Version }}-devel+{{ .ShortCommit }}"

archives:
  - id: "vlt"
    name_template: "vlt_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: true

    files:
      - UNLICENSE
      - systemd/vltd.service
      - src: scripts/install.sh
        dst: install.sh

    ids: [vlt, vltd]
    formats: [tar.gz]
