builds:
  - main: ./cmd/vlt
    id: "vlt"
    binary: vlt
  - main: ./cmd/vltd
    id: "vltd"
    binary: vltd

archives:
  - id: "vlt"
    format: tar.gz
    name_template: "vlt_{{ .Version }}_{{ .Os }}_{{ .Arch }}"