#!/bin/bash
set -euo pipefail

PATCH_FILE="vendor/modernc.org/sqlite/sqlite_patch.go"

cat >"$PATCH_FILE" <<EOF
// Patch: expose internal 'conn' as exported 'Conn' for serialization access
// NOTE: This file is auto-generated by patch_vendor.sh
package sqlite

// Conn is an exported alias for the internal [sqlite.conn] type.
//
// It is exposed to allow access to serialization methods
// such as Serialize and Deserialize.
type Conn = conn
EOF

echo "[vendor-patch] Applied: $PATCH_FILE"
