#!/bin/bash

set -euo pipefail

TEMPLATE="${1:-readme.templ.md}"
OUT="${2:-readme.md}"

TMP_README=$(mktemp)

cat <<EOF >"$TMP_README"
<!--
    This file is generated by gen-readme.sh.
    Do not edit this file directly.
    Instead, edit '${TEMPLATE}' and run the script.
-->
EOF

sed -e '/{{CONFIG}}/ {
    r assets/default-config.toml
    d
}' -e '/{{USAGE}}/ {
    r assets/usage.txt
    d
}' -e "s/{{COVERAGE}}/$(<assets/coverage)/g" \
    "$TEMPLATE" >>"$TMP_README"

mv "$TMP_README" "$OUT"

echo "generated $OUT from $TEMPLATE"
