name: golang-ci

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

env:
  GO_VERSION: 1.24

jobs:
  lint-and-test:
    name: lint & test
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/lint-and-test
        with:
          go-version: ${{env.GO_VERSION}}
